import fs from 'fs';

let content = fs.readFileSync('words.json', 'utf16le');
if (content.charCodeAt(0) === 0xFEFF) {
  content = content.slice(1);
}
let words = JSON.parse(content);

const frWordMap = {
  home: 'accueil',
  machine: 'machine',
  machines: 'machines',
  services: 'services',
  service: 'service',
  about: 'à propos',
  contact: 'contact',
  login: 'connexion',
  log: 'connexion',
  in: 'en',
  out: 'déconnexion',
  dashboard: 'tableau de bord',
  rentals: 'locations',
  rental: 'location',
  user: 'utilisateur',
  users: 'utilisateurs',
  management: 'gestion',
  staff: 'personnel',
  drivers: 'chauffeurs',
  finances: 'finances',
  settings: 'paramètres',
  notifications: 'notifications',
  account: 'compte',
  profile: 'profil',
  personal: 'personnel',
  information: 'informations',
  name: 'nom',
  email: 'email',
  phone: 'téléphone',
  number: 'numéro',
  update: 'mettre à jour',
  security: 'sécurité',
  change: 'modifier',
  password: 'mot de passe',
  current: 'actuel',
  new: 'nouveau',
  confirm: 'confirmer',
  save: 'enregistrer',
  changes: 'modifications',
  welcome: 'bienvenue',
  create: 'créer',
  register: 'inscrire',
  search: 'rechercher',
  no: 'aucun',
  found: 'trouvé',
  active: 'actif',
  pending: 'en attente',
  verified: 'vérifié',
  status: 'statut',
  available: 'disponible',
  rented: 'loué',
  maintenance: 'maintenance',
  total: 'total',
  cost: 'coût',
  payment: 'paiement',
  due: 'dû',
  message: 'message',
  send: 'envoyer',
  office: 'bureau',
  location: 'emplacement',
  support: 'assistance',
  company: 'entreprise',
  address: 'adresse',
  currency: 'devise',
  date: 'date',
  format: 'format',
  assign: 'assigner',
  task: 'tâche',
  cancel: 'annuler',
  confirm_assignment: "confirmer l'affectation",
};

const missing = words.filter(w => !(w in frWordMap));
console.log('Missing words:', missing.length);
fs.writeFileSync('missing-words.json', JSON.stringify(missing, null, 2));

